- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - none.yml
      paths:
        - vars
  tags:
    - sudo

- include_tasks: "install-{{ ansible_facts.os_family }}.yml"
  when: ansible_facts.pkg_mgr != 'unknown'
  tags:
    - sudo

- name: Create sudo groups
  group:
    name: "{{ item.name }}"
    state: present
  loop: "{{ sudo_groups }}"
  when: sudo_create_groups | bool
  tags:
    - sudo

- name: Configure sudoers file
  lineinfile:
    dest: "{{ sudo_sudoers_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
    validate: "{{ _sudo_validate_command }}"
  loop: "{{ sudo_sudoers_lines }}"
  tags:
    - sudo
    - sudoers

- name: Make sure {{ sudo_sudoers_d_path }} exists
  file:
    state: directory
    path: "{{ sudo_sudoers_d_path }}"
    owner: "{{ sudo_owner }}"
    group: "{{ _sudo_group | default(sudo_group) }}"
    mode: '0750'
  tags:
    - sudo

- name: Copy sudoers template
  template:
    src: ansible-sudoers.j2
    dest: "{{ sudo_sudoers_d_path }}/ansible"
    owner: "{{ sudo_owner }}"
    group: "{{ _sudo_group | default(sudo_group) }}"
    mode: '0440'
    validate: "{{ _sudo_validate_command }}"
  when: (sudo_users + sudo_groups) | length > 0
  tags:
    - sudo
